spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_springboot_microservice
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Abcds007
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
